version: '3.8'

services:
    # Kakao Proxy Server
    app:
        image: ghcr.io/${GITHUB_ACTOR}/moneed/kakao-proxy:${IMAGE_TAG:-latest}
        container_name: kakao-proxy
        restart: unless-stopped
        env_file:
            - .env.production
            - .env
        expose:
            - '8000'
        networks:
            - moneed-network
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
            interval: 30s
            timeout: 3s
            start_period: 5s
            retries: 3

    # Nginx Reverse Proxy
    nginx:
        image: nginx:alpine
        container_name: nginx-proxy
        restart: unless-stopped
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
            - ./nginx/ssl:/etc/nginx/ssl:ro
        depends_on:
            - app
        networks:
            - moneed-network

networks:
    moneed-network:
        driver: bridge
